name: Synchronization

on:
  repository_dispatch:
  schedule:
    - cron:  '0 */12 * * *'  # runs every 12 hours

jobs:
  sync:
    if: (github.event_name == 'repository_dispatch' && github.kevent.action == 'sync') ||
        (github.event_name == 'schedule')
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install hub
      uses: geertvdc/setup-hub@v1.0.0

    - name: Download scripts
      run: curl https://raw.githubusercontent.com/FriendsOfGalaxy/galaxy-integrations-updater/master/scripts.py --output ../scripts.py

    - name: Check and sync to PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
      run: python ../scripts.py sync
